// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoInstituição;

namespace ProjetoInstituição.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ProjetoInstituição.Entidades.Instituicao", b =>
                {
                    b.Property<int>("instId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("instId");

                    b.ToTable("INTITUICAO");
                });

            modelBuilder.Entity("ProjetoInstituição.Entidades.Professor", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Materias")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int>("instId")
                        .HasColumnType("int");

                    b.Property<int?>("instituicaoinstId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("instituicaoinstId");

                    b.ToTable("PROFESSOR");
                });

            modelBuilder.Entity("ProjetoInstituição.Entidades.Professor", b =>
                {
                    b.HasOne("ProjetoInstituição.Entidades.Instituicao", "instituicao")
                        .WithMany()
                        .HasForeignKey("instituicaoinstId");

                    b.Navigation("instituicao");
                });
#pragma warning restore 612, 618
        }
    }
}
